sudo: required

dist: bionic

language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE quotes_testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv
  - yarn
  - yarn dev

script:
  - vendor/bin/phpunit --printer Codedungeon\\\PHPUnitPrettyResultPrinter\\\Printer
  - php artisan dusk